// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base // import "github.com/gopub/protobuf/base"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneNumber struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_2ddb43b04ce3cc26, []int{0}
}
func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (dst *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(dst, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type IDList struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDList) Reset()         { *m = IDList{} }
func (m *IDList) String() string { return proto.CompactTextString(m) }
func (*IDList) ProtoMessage()    {}
func (*IDList) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_2ddb43b04ce3cc26, []int{1}
}
func (m *IDList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDList.Unmarshal(m, b)
}
func (m *IDList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDList.Marshal(b, m, deterministic)
}
func (dst *IDList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDList.Merge(dst, src)
}
func (m *IDList) XXX_Size() int {
	return xxx_messageInfo_IDList.Size(m)
}
func (m *IDList) XXX_DiscardUnknown() {
	xxx_messageInfo_IDList.DiscardUnknown(m)
}

var xxx_messageInfo_IDList proto.InternalMessageInfo

func (m *IDList) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type OpenID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenID) Reset()         { *m = OpenID{} }
func (m *OpenID) String() string { return proto.CompactTextString(m) }
func (*OpenID) ProtoMessage()    {}
func (*OpenID) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_2ddb43b04ce3cc26, []int{2}
}
func (m *OpenID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenID.Unmarshal(m, b)
}
func (m *OpenID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenID.Marshal(b, m, deterministic)
}
func (dst *OpenID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenID.Merge(dst, src)
}
func (m *OpenID) XXX_Size() int {
	return xxx_messageInfo_OpenID.Size(m)
}
func (m *OpenID) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenID.DiscardUnknown(m)
}

var xxx_messageInfo_OpenID proto.InternalMessageInfo

func (m *OpenID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenID) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type ListQuery struct {
	SinceId              int64    `protobuf:"varint,1,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_2ddb43b04ce3cc26, []int{3}
}
func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (dst *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(dst, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetSinceId() int64 {
	if m != nil {
		return m.SinceId
	}
	return 0
}

func (m *ListQuery) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*PhoneNumber)(nil), "gopub.protobuf.PhoneNumber")
	proto.RegisterType((*IDList)(nil), "gopub.protobuf.IDList")
	proto.RegisterType((*OpenID)(nil), "gopub.protobuf.OpenID")
	proto.RegisterType((*ListQuery)(nil), "gopub.protobuf.ListQuery")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_base_2ddb43b04ce3cc26) }

var fileDescriptor_base_2ddb43b04ce3cc26 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0x87, 0x95, 0x44, 0x0d, 0xed, 0x15, 0x55, 0xe8, 0x84, 0x50, 0xe8, 0x80, 0x42, 0xa6, 0x4e,
	0xcd, 0x00, 0x23, 0x13, 0x74, 0x20, 0x12, 0xe2, 0x91, 0x91, 0xa5, 0xc2, 0xf1, 0xd1, 0x7a, 0xa8,
	0x2f, 0xf2, 0x03, 0xa9, 0xff, 0x3d, 0x8a, 0xeb, 0x66, 0xf3, 0xe7, 0xbb, 0xfb, 0x74, 0xbf, 0x03,
	0x10, 0x3f, 0x96, 0xd6, 0xbd, 0x61, 0xc7, 0xb8, 0xd8, 0x71, 0xef, 0xc5, 0x09, 0x84, 0xff, 0xad,
	0x5e, 0x61, 0xfe, 0xb9, 0x67, 0x4d, 0xef, 0xfe, 0x20, 0xc8, 0xe0, 0x3d, 0x5c, 0x76, 0xec, 0xb5,
	0x33, 0xc7, 0x6d, 0xc7, 0x92, 0x8a, 0xa4, 0x4c, 0x56, 0xb3, 0x76, 0x1e, 0xff, 0x5e, 0x58, 0x12,
	0xde, 0x40, 0xae, 0x43, 0x73, 0x91, 0x86, 0x62, 0xa4, 0x6a, 0x09, 0x79, 0xb3, 0x79, 0x53, 0xd6,
	0xe1, 0x15, 0x64, 0x4a, 0xda, 0x22, 0x29, 0xb3, 0x55, 0xd6, 0x0e, 0xcf, 0xea, 0x11, 0xf2, 0x8f,
	0x9e, 0x74, 0xb3, 0xc1, 0x05, 0xa4, 0x4a, 0x46, 0x6d, 0xaa, 0x24, 0x2e, 0x61, 0xda, 0x1b, 0xfe,
	0x53, 0x72, 0xf4, 0x8d, 0x5c, 0x3d, 0xc1, 0x6c, 0xf0, 0x7d, 0x79, 0x32, 0x47, 0xbc, 0x85, 0xa9,
	0x55, 0xba, 0xa3, 0x6d, 0x1c, 0xcf, 0xda, 0x8b, 0xc0, 0x8d, 0xc4, 0x6b, 0x98, 0x84, 0x05, 0x83,
	0x60, 0xd2, 0x9e, 0xe0, 0xb9, 0xfc, 0xbe, 0xdb, 0x29, 0xb7, 0xf7, 0x62, 0xdd, 0xf1, 0xa1, 0x0e,
	0xb1, 0xeb, 0x73, 0xec, 0x7a, 0xb8, 0x88, 0xc8, 0x03, 0x3e, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0xe9, 0xfb, 0x53, 0x20, 0x01, 0x00, 0x00,
}
