// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base // import "github.com/gopub/protobuf/base"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoidValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidValue) Reset()         { *m = VoidValue{} }
func (m *VoidValue) String() string { return proto.CompactTextString(m) }
func (*VoidValue) ProtoMessage()    {}
func (*VoidValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{0}
}
func (m *VoidValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidValue.Unmarshal(m, b)
}
func (m *VoidValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidValue.Marshal(b, m, deterministic)
}
func (dst *VoidValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidValue.Merge(dst, src)
}
func (m *VoidValue) XXX_Size() int {
	return xxx_messageInfo_VoidValue.Size(m)
}
func (m *VoidValue) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidValue.DiscardUnknown(m)
}

var xxx_messageInfo_VoidValue proto.InternalMessageInfo

type BoolValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{1}
}
func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (dst *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(dst, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Int64Value struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Value) Reset()         { *m = Int64Value{} }
func (m *Int64Value) String() string { return proto.CompactTextString(m) }
func (*Int64Value) ProtoMessage()    {}
func (*Int64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{2}
}
func (m *Int64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Value.Unmarshal(m, b)
}
func (m *Int64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Value.Marshal(b, m, deterministic)
}
func (dst *Int64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Value.Merge(dst, src)
}
func (m *Int64Value) XXX_Size() int {
	return xxx_messageInfo_Int64Value.Size(m)
}
func (m *Int64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Value.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Value proto.InternalMessageInfo

func (m *Int64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64List struct {
	Value                []int64  `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{3}
}
func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (dst *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(dst, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{4}
}
func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (dst *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(dst, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StringList struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{5}
}
func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (dst *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(dst, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Int64Pair struct {
	First                int64    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second               int64    `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Pair) Reset()         { *m = Int64Pair{} }
func (m *Int64Pair) String() string { return proto.CompactTextString(m) }
func (*Int64Pair) ProtoMessage()    {}
func (*Int64Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{6}
}
func (m *Int64Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Pair.Unmarshal(m, b)
}
func (m *Int64Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Pair.Marshal(b, m, deterministic)
}
func (dst *Int64Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Pair.Merge(dst, src)
}
func (m *Int64Pair) XXX_Size() int {
	return xxx_messageInfo_Int64Pair.Size(m)
}
func (m *Int64Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Pair proto.InternalMessageInfo

func (m *Int64Pair) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Int64Pair) GetSecond() int64 {
	if m != nil {
		return m.Second
	}
	return 0
}

type StringPair struct {
	First                int64    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second               int64    `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringPair) Reset()         { *m = StringPair{} }
func (m *StringPair) String() string { return proto.CompactTextString(m) }
func (*StringPair) ProtoMessage()    {}
func (*StringPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{7}
}
func (m *StringPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringPair.Unmarshal(m, b)
}
func (m *StringPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringPair.Marshal(b, m, deterministic)
}
func (dst *StringPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringPair.Merge(dst, src)
}
func (m *StringPair) XXX_Size() int {
	return xxx_messageInfo_StringPair.Size(m)
}
func (m *StringPair) XXX_DiscardUnknown() {
	xxx_messageInfo_StringPair.DiscardUnknown(m)
}

var xxx_messageInfo_StringPair proto.InternalMessageInfo

func (m *StringPair) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *StringPair) GetSecond() int64 {
	if m != nil {
		return m.Second
	}
	return 0
}

type Int64StringPair struct {
	First                int64    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second               string   `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64StringPair) Reset()         { *m = Int64StringPair{} }
func (m *Int64StringPair) String() string { return proto.CompactTextString(m) }
func (*Int64StringPair) ProtoMessage()    {}
func (*Int64StringPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{8}
}
func (m *Int64StringPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64StringPair.Unmarshal(m, b)
}
func (m *Int64StringPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64StringPair.Marshal(b, m, deterministic)
}
func (dst *Int64StringPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64StringPair.Merge(dst, src)
}
func (m *Int64StringPair) XXX_Size() int {
	return xxx_messageInfo_Int64StringPair.Size(m)
}
func (m *Int64StringPair) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64StringPair.DiscardUnknown(m)
}

var xxx_messageInfo_Int64StringPair proto.InternalMessageInfo

func (m *Int64StringPair) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Int64StringPair) GetSecond() string {
	if m != nil {
		return m.Second
	}
	return ""
}

type ListQuery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SinceId              int64    `protobuf:"varint,2,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{9}
}
func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (dst *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(dst, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListQuery) GetSinceId() int64 {
	if m != nil {
		return m.SinceId
	}
	return 0
}

func (m *ListQuery) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Area struct {
	MinLat               float64  `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MaxLat               float64  `protobuf:"fixed64,2,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MinLng               float64  `protobuf:"fixed64,3,opt,name=min_lng,json=minLng,proto3" json:"min_lng,omitempty"`
	MaxLng               float64  `protobuf:"fixed64,4,opt,name=max_lng,json=maxLng,proto3" json:"max_lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{10}
}
func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (dst *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(dst, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetMinLat() float64 {
	if m != nil {
		return m.MinLat
	}
	return 0
}

func (m *Area) GetMaxLat() float64 {
	if m != nil {
		return m.MaxLat
	}
	return 0
}

func (m *Area) GetMinLng() float64 {
	if m != nil {
		return m.MinLng
	}
	return 0
}

func (m *Area) GetMaxLng() float64 {
	if m != nil {
		return m.MaxLng
	}
	return 0
}

type Coordinate struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_3231e92fab4e3ed3, []int{11}
}
func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (dst *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(dst, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinate) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func init() {
	proto.RegisterType((*VoidValue)(nil), "gopub.protobuf.VoidValue")
	proto.RegisterType((*BoolValue)(nil), "gopub.protobuf.BoolValue")
	proto.RegisterType((*Int64Value)(nil), "gopub.protobuf.Int64Value")
	proto.RegisterType((*Int64List)(nil), "gopub.protobuf.Int64List")
	proto.RegisterType((*StringValue)(nil), "gopub.protobuf.StringValue")
	proto.RegisterType((*StringList)(nil), "gopub.protobuf.StringList")
	proto.RegisterType((*Int64Pair)(nil), "gopub.protobuf.Int64Pair")
	proto.RegisterType((*StringPair)(nil), "gopub.protobuf.StringPair")
	proto.RegisterType((*Int64StringPair)(nil), "gopub.protobuf.Int64StringPair")
	proto.RegisterType((*ListQuery)(nil), "gopub.protobuf.ListQuery")
	proto.RegisterType((*Area)(nil), "gopub.protobuf.Area")
	proto.RegisterType((*Coordinate)(nil), "gopub.protobuf.Coordinate")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_base_3231e92fab4e3ed3) }

var fileDescriptor_base_3231e92fab4e3ed3 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4b, 0xf3, 0x30,
	0x1c, 0xc7, 0x69, 0xf7, 0xda, 0xdf, 0x60, 0x0f, 0x84, 0x87, 0xe7, 0xa9, 0x22, 0xb2, 0xd5, 0xcb,
	0x4e, 0xdb, 0x41, 0x11, 0xf4, 0x22, 0x4e, 0x10, 0x06, 0x3b, 0xe8, 0x84, 0x1d, 0xbc, 0x8c, 0xb4,
	0xcd, 0xe2, 0x4f, 0xba, 0x64, 0xa4, 0x89, 0xcc, 0xff, 0x5e, 0x9a, 0xb4, 0xdd, 0xc0, 0x5d, 0xf4,
	0xd6, 0x4f, 0xbe, 0x6f, 0x29, 0x04, 0x20, 0xa6, 0x39, 0x1b, 0x6f, 0x95, 0xd4, 0x92, 0xf4, 0xb9,
	0xdc, 0x9a, 0xd8, 0x41, 0x6c, 0xd6, 0x51, 0x0f, 0x82, 0xa5, 0xc4, 0x74, 0x49, 0x33, 0xc3, 0xa2,
	0x21, 0x04, 0x53, 0x29, 0x33, 0x0b, 0xe4, 0x2f, 0xb4, 0x3e, 0x8a, 0x8f, 0xd0, 0x1b, 0x78, 0xa3,
	0xee, 0xc2, 0x41, 0x14, 0x01, 0xcc, 0x84, 0xbe, 0xbe, 0x3a, 0xe2, 0x69, 0x54, 0x9e, 0x21, 0x04,
	0xd6, 0x33, 0xc7, 0x5c, 0x1f, 0x5a, 0x1a, 0x7b, 0xcb, 0x05, 0xf4, 0x5e, 0xb4, 0x42, 0xc1, 0x8f,
	0xf4, 0x04, 0x07, 0x5b, 0xce, 0xf4, 0xbd, 0xa8, 0xf6, 0xdc, 0x94, 0x5b, 0x4f, 0x14, 0x55, 0x61,
	0x59, 0xa3, 0xca, 0x75, 0x75, 0x1d, 0x0b, 0xe4, 0x1f, 0xb4, 0x73, 0x96, 0x48, 0x91, 0x86, 0xbe,
	0x3d, 0x2e, 0x29, 0xba, 0xad, 0xea, 0x7f, 0x91, 0xbd, 0x83, 0x3f, 0x76, 0xf6, 0x87, 0x05, 0x41,
	0x5d, 0x30, 0x87, 0xa0, 0xf8, 0xab, 0x67, 0xc3, 0xd4, 0x27, 0xe9, 0x83, 0x8f, 0x69, 0x99, 0xf3,
	0x31, 0x25, 0x27, 0xd0, 0xcd, 0x51, 0x24, 0x6c, 0x85, 0xd5, 0x6e, 0xc7, 0xf2, 0x2c, 0x2d, 0x56,
	0x12, 0x69, 0x84, 0x0e, 0x1b, 0x03, 0x6f, 0xd4, 0x5a, 0x38, 0x88, 0xde, 0xa1, 0x79, 0xaf, 0x18,
	0x25, 0xff, 0xa1, 0xb3, 0x41, 0xb1, 0xca, 0xa8, 0xbb, 0x85, 0xb7, 0x68, 0x6f, 0x50, 0xcc, 0xa9,
	0xb6, 0x02, 0xdd, 0x59, 0xc1, 0x2f, 0x05, 0xba, 0xab, 0x84, 0x22, 0x21, 0xb8, 0x6d, 0x2c, 0x13,
	0x82, 0xd7, 0x09, 0xc1, 0xc3, 0xe6, 0x3e, 0x21, 0x78, 0xf4, 0x08, 0xf0, 0x20, 0xa5, 0x4a, 0x51,
	0x50, 0xcd, 0xc8, 0x19, 0x04, 0x99, 0x14, 0x1c, 0xb5, 0x49, 0x59, 0xb9, 0xb9, 0x3f, 0x20, 0xa7,
	0xd0, 0xcd, 0xa8, 0x76, 0xa2, 0xdb, 0xad, 0x79, 0x3a, 0x78, 0x3d, 0xe7, 0xa8, 0xdf, 0x4c, 0x3c,
	0x4e, 0xe4, 0x66, 0x62, 0x9f, 0xe5, 0xa4, 0x7a, 0x96, 0x93, 0xe2, 0xc5, 0xc6, 0x6d, 0x8b, 0x97,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x18, 0xcf, 0x60, 0xc0, 0x02, 0x00, 0x00,
}
